// GST Calculator Application
// Author: Generated by AI assistant
// Description: Provides single amount GST calculations (inclusive/exclusive) and itemized multi-row calculator with CGST/SGST/IGST split, rounding, copy & print utilities.

(() => {
	'use strict';

	/* ===============================
		 Utilities
	=============================== */
	const qs = (sel, ctx = document) => ctx.querySelector(sel);
	const qsa = (sel, ctx = document) => Array.from(ctx.querySelectorAll(sel));

	const parseNum = (val) => {
		if (typeof val === 'number') return val;
		if (!val) return 0;
		const cleaned = String(val).replace(/,/g, '').trim();
		if (cleaned === '') return 0;
		const num = Number(cleaned);
		return isNaN(num) ? 0 : num;
	};

	const rounders = {
		normal: (v) => Number(v.toFixed(2)),
		up: (v) => Math.ceil(v * 100) / 100,
		down: (v) => Math.floor(v * 100) / 100,
	};

	const formatMoney = (n) => (isNaN(n) ? '0.00' : n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }));

	const getSelected = (name, form = document) => {
		const el = form.querySelector(`input[name="${name}"]:checked`);
		return el ? el.value : null;
	};

	/* ===============================
		 Theme Toggle
	=============================== */
	const themeToggle = qs('#themeToggle');
	const THEME_KEY = 'gst_theme';
	function applyStoredTheme() {
		const saved = localStorage.getItem(THEME_KEY);
		if (saved === 'light') {
			document.body.classList.add('light');
			document.body.classList.remove('dark');
		} else if (saved === 'dark') {
			document.body.classList.add('dark');
			document.body.classList.remove('light');
		} else {
			// Detect preference
			if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
				document.body.classList.add('dark');
			} else {
				document.body.classList.add('light');
			}
		}
	}
	function toggleTheme() {
		if (document.body.classList.contains('dark')) {
			document.body.classList.remove('dark');
			document.body.classList.add('light');
			localStorage.setItem(THEME_KEY, 'light');
			themeToggle.setAttribute('aria-pressed', 'false');
		} else {
			document.body.classList.remove('light');
			document.body.classList.add('dark');
			localStorage.setItem(THEME_KEY, 'dark');
			themeToggle.setAttribute('aria-pressed', 'true');
		}
	}
	if (themeToggle) themeToggle.addEventListener('click', toggleTheme);
	applyStoredTheme();

	/* ===============================
		 Single Calculation
	=============================== */
	const singleForm = qs('#singleForm');
	const amountInput = qs('#amountInput');
	const rateSelect = qs('#rateSelect');
	const customRate = qs('#customRate');
	const singleResult = qs('#singleResult');
	const amountHint = qs('#amountModeHint');
	const roundingSel = qs('#rounding');
	const clearSingle = qs('#clearSingle');

	rateSelect.addEventListener('change', () => {
		if (rateSelect.value === 'custom') {
			customRate.classList.remove('hidden');
			customRate.focus();
		} else {
			customRate.classList.add('hidden');
		}
	});

	singleForm.addEventListener('change', (e) => {
		if (e.target.name === 'mode') {
			const mode = getSelected('mode', singleForm);
			amountHint.textContent = mode === 'inclusive' ? 'Enter gross amount (includes GST).' : 'Enter base amount (exclusive).';
		}
	});

	function computeSingle({ amt, rate, mode, supplyType, rounding }) {
		const round = rounders[rounding] || rounders.normal;
		let base = 0, gst = 0, gross = 0;
		rate = rate || 0;
		if (mode === 'inclusive') {
			gross = amt;
			base = amt / (1 + rate / 100);
			gst = gross - base;
		} else { // exclusive
			base = amt;
			gst = base * rate / 100;
			gross = base + gst;
		}
		base = round(base); gst = round(gst); gross = round(gross);
		let cgst = 0, sgst = 0, igst = 0;
		if (supplyType === 'intra') {
			cgst = round(gst / 2); sgst = round(gst / 2);
		} else { igst = gst; }
		return { base, gst, gross, rate, cgst, sgst, igst };
	}

	function renderSingleResult(data) {
		const { base, gst, gross, rate, cgst, sgst, igst } = data;
		singleResult.innerHTML = `
			<div class="result-box"><h3>Taxable Value</h3><div class="value">₹ ${formatMoney(base)}</div></div>
			<div class="result-box"><h3>GST @ ${rate}%</h3><div class="value">₹ ${formatMoney(gst)}</div></div>
			${cgst ? `<div class="result-box"><h3>CGST</h3><div class="value">₹ ${formatMoney(cgst)}</div></div>` : ''}
			${sgst ? `<div class="result-box"><h3>SGST</h3><div class="value">₹ ${formatMoney(sgst)}</div></div>` : ''}
			${igst ? `<div class="result-box"><h3>IGST</h3><div class="value">₹ ${formatMoney(igst)}</div></div>` : ''}
			<div class="result-box accent"><h3>Total (Gross)</h3><div class="value">₹ ${formatMoney(gross)}</div></div>
		`;
	}

	singleForm.addEventListener('submit', (e) => {
		e.preventDefault();
		const amt = parseNum(amountInput.value);
		const mode = getSelected('mode', singleForm);
		const supplyType = getSelected('supplyType', singleForm);
		let rateVal = rateSelect.value === 'custom' ? parseNum(customRate.value) : parseNum(rateSelect.value);
		const rounding = roundingSel.value;
		if (rateVal < 0) rateVal = 0;
		if (amt <= 0) {
			amountInput.classList.add('error');
			amountInput.focus();
			return;
		} else amountInput.classList.remove('error');
		const result = computeSingle({ amt, rate: rateVal, mode, supplyType, rounding });
		renderSingleResult(result);
	});

	clearSingle.addEventListener('click', () => {
		singleForm.reset();
		customRate.classList.add('hidden');
		singleResult.innerHTML = '';
	});

	/* ===============================
		 Itemized Calculator
	=============================== */
	const addItemBtn = qs('#addItem');
	const itemBody = qs('#itemBody');
	const rowTemplate = qs('#rowTemplate');
	const itemSummary = qs('#itemSummary');
	const bulkSample = qs('#bulkSample');

	function addRow(preset = {}) {
		const clone = document.importNode(rowTemplate.content, true);
		const tr = clone.querySelector('tr');
		const desc = tr.querySelector('.desc');
		const modeSel = tr.querySelector('.mode');
		const amtEl = tr.querySelector('.amt');
		const rateEl = tr.querySelector('.rate');
		desc.value = preset.desc || '';
		modeSel.value = preset.mode || 'exclusive';
		amtEl.value = preset.amount != null ? preset.amount : '';
		rateEl.value = preset.rate != null ? preset.rate : '';
		itemBody.appendChild(tr);
		renumberRows();
	}

	function renumberRows() {
		qsa('.row-index', itemBody).forEach((cell, idx) => cell.textContent = idx + 1);
	}

	function computeRow(amt, rate, mode) {
		amt = parseNum(amt); rate = parseNum(rate);
		if (amt <= 0 || rate < 0) return { gst: 0, net: 0, gross: 0 };
		if (mode === 'inclusive') {
			const gross = amt;
			const net = gross / (1 + rate / 100);
			const gst = gross - net;
			return { gst, net, gross };
		} else {
			const net = amt;
			const gst = net * rate / 100;
			const gross = net + gst;
			return { gst, net, gross };
		}
	}

	function updateItemRow(tr) {
		const amtEl = tr.querySelector('.amt');
		const rateEl = tr.querySelector('.rate');
		const modeSel = tr.querySelector('.mode');
		const gstCell = tr.querySelector('.gst');
		const netCell = tr.querySelector('.net');
		const grossCell = tr.querySelector('.gross');
		const { gst, net, gross } = computeRow(amtEl.value, rateEl.value, modeSel.value);
		gstCell.dataset.value = gst; gstCell.textContent = formatMoney(gst);
		netCell.dataset.value = net; netCell.textContent = formatMoney(net);
		grossCell.dataset.value = gross; grossCell.textContent = formatMoney(gross);
	}

	function summarizeItems() {
		const rounding = roundingSel.value;
		const round = rounders[rounding] || rounders.normal;
		let totalGST = 0, totalNet = 0, totalGross = 0;
		qsa('#itemBody tr').forEach(tr => {
			updateItemRow(tr); // ensure current
			totalGST += parseNum(tr.querySelector('.gst').dataset.value);
			totalNet += parseNum(tr.querySelector('.net').dataset.value);
			totalGross += parseNum(tr.querySelector('.gross').dataset.value);
		});
		totalGST = round(totalGST); totalNet = round(totalNet); totalGross = round(totalGross);
		itemSummary.innerHTML = `
			<span class="summary-pill"><strong>Items:</strong> ${qsa('#itemBody tr').length}</span>
			<span class="summary-pill"><strong>Taxable:</strong> ₹ ${formatMoney(totalNet)}</span>
			<span class="summary-pill"><strong>GST:</strong> ₹ ${formatMoney(totalGST)}</span>
			<span class="summary-pill"><strong>Gross:</strong> ₹ ${formatMoney(totalGross)}</span>
		`;
	}

	function handleItemInput(e) {
		const tr = e.target.closest('tr');
		if (!tr) return;
		updateItemRow(tr);
		summarizeItems();
	}

	addItemBtn.addEventListener('click', () => {
		addRow();
	});

	bulkSample.addEventListener('click', () => {
		if (qsa('#itemBody tr').length === 0) {
			addRow({ desc: 'Consulting Service', mode: 'exclusive', amount: 50000, rate: 18 });
			addRow({ desc: 'Software License', mode: 'exclusive', amount: 12000, rate: 18 });
			addRow({ desc: 'Stationery (Incl)', mode: 'inclusive', amount: 1180, rate: 18 });
			summarizeItems();
		}
	});

	itemBody.addEventListener('input', handleItemInput);
	itemBody.addEventListener('change', handleItemInput);
	itemBody.addEventListener('click', (e) => {
		if (e.target.classList.contains('row-del')) {
			e.preventDefault();
			const tr = e.target.closest('tr');
			tr?.remove();
			renumberRows();
			summarizeItems();
		}
	});

	/* Keyboard navigation helpers */
	itemBody.addEventListener('keydown', (e) => {
		if (e.key === 'Enter') {
			e.preventDefault();
			const inputs = qsa('input.desc, select.mode, input.amt, input.rate', itemBody);
			const idx = inputs.indexOf(e.target);
			if (idx > -1) {
				const next = inputs[idx + 1];
				if (next) next.focus();
				else addRow();
			}
		}
	});

	/* ===============================
		 Share / Copy & Print / Reset
	=============================== */
	const shareBtn = qs('#shareBtn');
	const printBtn = qs('#printBtn');
	const resetAll = qs('#resetAll');

	async function copySummary() {
		const singleText = singleResult.textContent.trim().replace(/\s+/g, ' ');
		const itemRows = qsa('#itemBody tr').map((tr, i) => {
			const d = tr.querySelector('.desc').value || `Item ${i+1}`;
			const mode = tr.querySelector('.mode').value[0].toUpperCase();
			const amt = tr.querySelector('.amt').value;
			const rate = tr.querySelector('.rate').value;
			const gst = tr.querySelector('.gst').textContent;
			const net = tr.querySelector('.net').textContent;
			const gross = tr.querySelector('.gross').textContent;
			return `${d} | ${mode} | Amt: ${amt} | Rate: ${rate}% | GST: ${gst} | Net: ${net} | Gross: ${gross}`;
		}).join('\n');
		const summaryFooter = itemSummary.textContent.trim().replace(/\s+/g, ' ');
		const text = `GST Calculator Summary\nSingle: ${singleText || 'N/A'}\nItems:\n${itemRows || 'No items'}\n${summaryFooter}`;
		try {
			await navigator.clipboard.writeText(text);
			shareBtn.textContent = 'Copied!';
			setTimeout(() => shareBtn.textContent = '📋', 1600);
		} catch (err) {
			alert('Copy failed');
		}
	}
	if (shareBtn) shareBtn.addEventListener('click', copySummary);
	if (printBtn) printBtn.addEventListener('click', () => window.print());
	if (resetAll) resetAll.addEventListener('click', () => {
		if (!confirm('Clear all data?')) return;
		singleForm.reset();
		customRate.classList.add('hidden');
		singleResult.innerHTML = '';
		itemBody.innerHTML = '';
		itemSummary.innerHTML = '';
	});

	/* ===============================
		 Accessibility Helpers
	=============================== */
	// Manage focus outline for keyboard only
	function handleFirstTab(e) {
		if (e.key === 'Tab') {
			document.body.classList.add('user-is-tabbing');
			window.removeEventListener('keydown', handleFirstTab);
		}
	}
	window.addEventListener('keydown', handleFirstTab);

	// Auto add first row for convenience
	addRow();
	summarizeItems();
})();
